import "./globals.css";
import { CartProvider } from "./utilities/cartContex";

export const metadata = {
    title: "Medisource",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <CartProvider>{children}</CartProvider>
            </body>
        </html>
    );
}
